//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFitness.Translation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NutrientTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NutrientTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarbonFitness.Translation.Resources.NutrientTranslation", typeof(NutrientTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkohol (g).
        /// </summary>
        internal static string AlcoholInG {
            get {
                return ResourceManager.GetString("AlcoholInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatten (g).
        /// </summary>
        internal static string AquaInG {
            get {
                return ResourceManager.GetString("AquaInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askorbinsyra (mg).
        /// </summary>
        internal static string AscorbicAcidInmG {
            get {
                return ResourceManager.GetString("AscorbicAcidInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aska (g).
        /// </summary>
        internal static string AshInG {
            get {
                return ResourceManager.GetString("AshInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalcium (mg).
        /// </summary>
        internal static string CalciumInmG {
            get {
                return ResourceManager.GetString("CalciumInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolhydrat (g).
        /// </summary>
        internal static string CarbonHydrateInG {
            get {
                return ResourceManager.GetString("CarbonHydrateInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karoten (µg).
        /// </summary>
        internal static string CaroteneInµG {
            get {
                return ResourceManager.GetString("CaroteneInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolesterol (mg).
        /// </summary>
        internal static string CholesteroleInmG {
            get {
                return ResourceManager.GetString("CholesteroleInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disackarider (g).
        /// </summary>
        internal static string DisaccharidesInG {
            get {
                return ResourceManager.GetString("DisaccharidesInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D vitamin (µg).
        /// </summary>
        internal static string DVitaminInµG {
            get {
                return ResourceManager.GetString("DVitaminInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energi (Kcal).
        /// </summary>
        internal static string EnergyInKcal {
            get {
                return ResourceManager.GetString("EnergyInKcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energi (kJ).
        /// </summary>
        internal static string EnergyInKJ {
            get {
                return ResourceManager.GetString("EnergyInKJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E vitamin (mg).
        /// </summary>
        internal static string EVitaminInmG {
            get {
                return ResourceManager.GetString("EVitaminInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C12 (g).
        /// </summary>
        internal static string FatAcidC12InG {
            get {
                return ResourceManager.GetString("FatAcidC12InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C14 (g).
        /// </summary>
        internal static string FatAcidC14InG {
            get {
                return ResourceManager.GetString("FatAcidC14InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C16:1 (g).
        /// </summary>
        internal static string FatAcidC16_1InG {
            get {
                return ResourceManager.GetString("FatAcidC16_1InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C16 (g).
        /// </summary>
        internal static string FatAcidC16InG {
            get {
                return ResourceManager.GetString("FatAcidC16InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C18:1 (g).
        /// </summary>
        internal static string FatAcidC18_1InG {
            get {
                return ResourceManager.GetString("FatAcidC18_1InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C18:2 (g).
        /// </summary>
        internal static string FatAcidC18_2InG {
            get {
                return ResourceManager.GetString("FatAcidC18_2InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C18:3 (g).
        /// </summary>
        internal static string FatAcidC18_3InG {
            get {
                return ResourceManager.GetString("FatAcidC18_3InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C18 (g).
        /// </summary>
        internal static string FatAcidC18InG {
            get {
                return ResourceManager.GetString("FatAcidC18InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C20:4 (g).
        /// </summary>
        internal static string FatAcidC20_4InG {
            get {
                return ResourceManager.GetString("FatAcidC20_4InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C20:5 (g).
        /// </summary>
        internal static string FatAcidC20_5InG {
            get {
                return ResourceManager.GetString("FatAcidC20_5InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C20 (g).
        /// </summary>
        internal static string FatAcidC20InG {
            get {
                return ResourceManager.GetString("FatAcidC20InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C22:5 (g).
        /// </summary>
        internal static string FatAcidC22_5InG {
            get {
                return ResourceManager.GetString("FatAcidC22_5InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C22:6 (g).
        /// </summary>
        internal static string FatAcidC22_6InG {
            get {
                return ResourceManager.GetString("FatAcidC22_6InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettsyra C4-C10 (g).
        /// </summary>
        internal static string FatAcidC4C10InG {
            get {
                return ResourceManager.GetString("FatAcidC4C10InG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fett (g).
        /// </summary>
        internal static string FatInG {
            get {
                return ResourceManager.GetString("FatInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrer (g).
        /// </summary>
        internal static string FibresInG {
            get {
                return ResourceManager.GetString("FibresInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folat (µg).
        /// </summary>
        internal static string FolicAcidInµG {
            get {
                return ResourceManager.GetString("FolicAcidInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Järn (mg).
        /// </summary>
        internal static string IronInmG {
            get {
                return ResourceManager.GetString("IronInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium (mg).
        /// </summary>
        internal static string MagnesiumInmG {
            get {
                return ResourceManager.GetString("MagnesiumInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monosackarider (g).
        /// </summary>
        internal static string MonosaccharidesInG {
            get {
                return ResourceManager.GetString("MonosaccharidesInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkelomättade fettsyror (g).
        /// </summary>
        internal static string MonoUnSaturatedFatInG {
            get {
                return ResourceManager.GetString("MonoUnSaturatedFatInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natrium (mg).
        /// </summary>
        internal static string NatriumInmG {
            get {
                return ResourceManager.GetString("NatriumInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niacinekvivalent (mg).
        /// </summary>
        internal static string NiacinEquivalentInmG {
            get {
                return ResourceManager.GetString("NiacinEquivalentInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niacin (mg).
        /// </summary>
        internal static string NiacinInmG {
            get {
                return ResourceManager.GetString("NiacinInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fosfor (mg).
        /// </summary>
        internal static string PhosphorusInmG {
            get {
                return ResourceManager.GetString("PhosphorusInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleromättade fettsyror (g).
        /// </summary>
        internal static string PolyUnSaturatedFatInG {
            get {
                return ResourceManager.GetString("PolyUnSaturatedFatInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalium (mg).
        /// </summary>
        internal static string PotassiumInmG {
            get {
                return ResourceManager.GetString("PotassiumInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein (g).
        /// </summary>
        internal static string ProteinInG {
            get {
                return ResourceManager.GetString("ProteinInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retinolekvivalent (µg).
        /// </summary>
        internal static string RetinolEquivalentInµG {
            get {
                return ResourceManager.GetString("RetinolEquivalentInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retinol (µg).
        /// </summary>
        internal static string RetinolInµG {
            get {
                return ResourceManager.GetString("RetinolInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riboflavin (mg).
        /// </summary>
        internal static string RiboflavinInmG {
            get {
                return ResourceManager.GetString("RiboflavinInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mättade fettsyror (g).
        /// </summary>
        internal static string SaturatedFatInG {
            get {
                return ResourceManager.GetString("SaturatedFatInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selen (µg).
        /// </summary>
        internal static string SeleniumInµG {
            get {
                return ResourceManager.GetString("SeleniumInµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sackaros (g).
        /// </summary>
        internal static string SucroseInG {
            get {
                return ResourceManager.GetString("SucroseInG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiamin (mg).
        /// </summary>
        internal static string ThiamineInmG {
            get {
                return ResourceManager.GetString("ThiamineInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokoferol (mg).
        /// </summary>
        internal static string TokopherolInmG {
            get {
                return ResourceManager.GetString("TokopherolInmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B12 (µg).
        /// </summary>
        internal static string VitaminB12InµG {
            get {
                return ResourceManager.GetString("VitaminB12InµG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B6 (mg).
        /// </summary>
        internal static string VitaminB6InmG {
            get {
                return ResourceManager.GetString("VitaminB6InmG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avfall (%).
        /// </summary>
        internal static string WasteInPercent {
            get {
                return ResourceManager.GetString("WasteInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zink (mg).
        /// </summary>
        internal static string ZincInmG {
            get {
                return ResourceManager.GetString("ZincInmG", resourceCulture);
            }
        }
    }
}
