//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = true)]
public class value {
	/// <remarks/>
	[XmlAttribute()]
	public string xid { get; set; }

	/// <remarks/>
	[XmlText()]
	public string Value { get; set; }
}

/// <remarks/>
[GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(ElementName = "chart", Namespace = "", IsNullable = false)]
public class AmChartData {
	/// <remarks/>
	[XmlElement("series", typeof(value[]), Form = XmlSchemaForm.Unqualified)]
	public value[] DataPoints { get; set; }

	[XmlElement("graphs", typeof(chartGraphs), Form = XmlSchemaForm.Unqualified)]
	public chartGraphs GraphRoot { get; set; }
}

/// <remarks/>
[GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
public class chartGraphs {

	/// <remarks/>
	[XmlElement("graph", Form = XmlSchemaForm.Unqualified)]
	public chartGraphsGraph[] Graphs { get; set; }
}

/// <remarks/>
[GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
public class chartGraphsGraph {
	/// <remarks/>
	[XmlElement("value", IsNullable = true)]
	public value[] value { get; set; }

	/// <remarks/>
	[XmlAttribute()]
	public string gid { get; set; }
}